### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by limelect** [DeveloppeurPascal/Video-Merger#16]
Filter file to what allowed
Or is it for all files?
         cmd := cmd + ' -filter_complex ''concat=n=' +
         cmd: supposed to start with?
Delete file in file pan

**Comment by DeveloppeurPascal** [comment]
Hi

I'll explain the FFmpeg command soon like for https://github.com/DeveloppeurPascal/LeTempsDUneTomate

In VideoMerger you have to choose the files you want to join : add the number of selectors and choose one file in each. I suggest to add the selectors and close/open the program to avoid #12 bug.

They will be used as entry files in FFmpeg (the first part of "cmd" is the list of input files).

**Comment by DeveloppeurPascal** [comment]
The first public version has been released. You can download the installer from https://github.com/DeveloppeurPascal/Video-Merger/releases
